// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn6ccsgGcd6M1FfrHFcNi-6wIFuqGfS5o',
    appId: '1:612470815334:android:bb5787f58bacc1e87c4ba7',
    messagingSenderId: '612470815334',
    projectId: 'buzz-ai-f6841',
    databaseURL:
        'https://buzz-ai-f6841-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buzz-ai-f6841.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEgLwWsS2U2hHj6XIWVd9vYbMq92RXYVo',
    appId: '1:612470815334:ios:1dbd3dc5dae67c047c4ba7',
    messagingSenderId: '612470815334',
    projectId: 'buzz-ai-f6841',
    databaseURL:
        'https://buzz-ai-f6841-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buzz-ai-f6841.appspot.com',
    iosClientId:
        '612470815334-vmt6d6sq913ss5hjfov0bm3c57tm0f6t.apps.googleusercontent.com',
    iosBundleId: 'com.piyushlimited.buzzai',
  );
}
